apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.clusterName }}-external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{ .Values.clusterName }}
  forProvider:
    tags:
      giantswarm.io/cluster: {{ .Values.clusterName }}
      managed-by: "external-dns-crossplane-resources"
      sigs.k8s.io/cluster-api-provider-aws/cluster/{{ .Values.clusterName }}: owned
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {{- $oidcDomains := include "oidcDomains" . | fromJsonArray -}}
          {{- range $index, $oidcDomain := $oidcDomains -}}
          {{- if not (eq $index 0) }}, {{ end }}{
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:{{ required "awsPartition from aws-crossplane-cluster-config-operator is not filled yet" $.Values.awsPartition }}:iam::{{ required "accountID from aws-crossplane-cluster-config-operator is not filled yet" $.Values.accountID }}:oidc-provider/{{ $oidcDomain }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringLike": {
                "{{ $oidcDomain }}:sub": "system:serviceaccount:*:*external-dns*"
              }
            }
          }
          {{- end }}
        ]
      }
    inlinePolicy:
      - name: external-dns-policy
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Action": "route53:ChangeResourceRecordSets",
                "Resource": [
                  "arn:{{ required "awsPartition from aws-crossplane-cluster-config-operator is not filled yet" $.Values.awsPartition }}:route53:::hostedzone/*"
                ],
                "Effect": "Allow"
              },
              {
                "Action": [
                  "route53:ListHostedZones",
                  "route53:ListResourceRecordSets",
                  "route53:ListTagsForResource"
                ],
                "Resource": "*",
                "Effect": "Allow"
              }
            ]
          }
