{{- if eq .Values.provider "aks" }}
apiVersion: crossplane.giantswarm.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: {{ .Values.clusterName }}-external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  clusterName: {{ .Values.clusterName }}
  provider: {{ .Values.provider }}
  location: {{ .Values.azure.location }}
  resourceGroupName: {{ .Values.clusterName }}
  subject: system:serviceaccount:{{ .Release.Namespace }}:external-dns
  subscriptionID: {{ .Values.azure.subscriptionID }}
  template: |
    env:
    - name: AZURE_FEDERATED_TOKEN_FILE
      value: /var/run/secrets/azure/tokens/identity-token
    - name: AZURE_AUTHORITY_HOST
      value: https://login.microsoftonline.com/
    - name: AZURE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: clientID
          name: external-dns
    - name: AZURE_TENANT_ID
      valueFrom:
        secretKeyRef:
          key: tenantID
          name: external-dns
    extraVolumes:
    - name: azure-identity-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: api://AzureADTokenExchange
              expirationSeconds: 3600
              path: identity-token
    extraVolumeMounts:
      - mountPath: /var/run/secrets/azure/tokens
        name: azure-identity-token
        readOnly: true
    secretConfiguration:
      data:
        clientID: "${clientID}"
        tenantID: "${tenantID}"
        azure.json: |-
          {
            "clientId": "${clientID}",
            "subscriptionId": {{ .Values.azure.subscriptionID | quote }},
            "resourceGroup": {{ .Values.clusterName | quote }},
            "resourceGroupName": {{ .Values.clusterName | quote }},
            "useWorkloadIdentityExtension": true
          }
      enabled: true
      mountPath: /etc/kubernetes
{{- end }}
