{{- if eq .Values.provider "aks" }}
apiVersion: crossplane.giantswarm.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: {{ .Values.clusterName }}-external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  clusterName: {{ .Values.clusterName }}
  provider: {{ .Values.provider }}
  location: {{ .Values.azure.location }}
  resourceGroupName: {{ .Values.clusterName }}
  subject: system:serviceaccount:kube-system:external-dns
  subscriptionID: {{ .Values.azure.subscriptionID }}
  template: |
    secretConfiguration:
      data:
        clientID: "${clientID}"
        tenantID: "${tenantID}"
        azure.json: |-
          {
            "clientId": "${clientID}",
            "subscriptionId": {{ .Values.azure.subscriptionID | quote }},
            "resourceGroup": {{ .Values.clusterName | quote }},
            "resourceGroupName": {{ .Values.clusterName | quote }},
            "useWorkloadIdentityExtension": true
          }
      enabled: true
      mountPath: /etc/kubernetes
{{- end }}
