apiVersion: v2
appVersion: 0.0.1
# Please make sure your name DOES NOT end in "app" or "-app".
name: external-dns-crossplane-resources
# Please describe what the app provides in a sentence or two.
description: Crossplane Resources for External DNS
home: https://github.com/giantswarm/external-dns-crossplane-resources
icon: https://s.giantswarm.io/app-icons/aws/2/light.svg
sources:
  - https://github.com/giantswarm/external-dns-crossplane-resources
version: 0.1.5
annotations:
  application.giantswarm.io/team: phoenix
